import React, { useEffect, useState } from 'react';
import { 
  CheckCircle, 
  XCircle, 
  HelpCircle, 
  Clock, 
  Zap, 
  ChevronRight, 
  ArrowRight, 
  BookOpen 
} from 'lucide-react';
import { db } from '../storage/db';
import { LearningEngine } from '../learning-engine/engine';
import { TopicMetadata, KnowledgeNode } from '../types';

interface Question {
  id: string;
  topicId: string;
  prompt: string;
  options: string[];
  correctIndex: number;
  hint: string;
  explanation: string;
}

// Built-in question database representing high-fidelity curriculum nodes
const QUESTION_BANK: Record<string, Question[]> = {
  python_basics: [
    {
      id: 'qb_py_1',
      topicId: 'python_basics',
      prompt: 'What is the correct syntax to create a list of strings in Python?',
      options: [
        'fruits = "apple", "banana", "cherry"',
        'fruits = ["apple", "banana", "cherry"]',
        'fruits = (["apple"], ["banana"])',
        'fruits = {apple, banana, cherry}'
      ],
      correctIndex: 1,
      hint: 'Lists in Python are defined using square brackets `[]` and items are comma-separated.',
      explanation: 'Square brackets `[]` are used to define lists. Parentheses `()` are for tuples, and curly braces `{}` are for sets or dictionaries.'
    },
    {
      id: 'qb_py_2',
      topicId: 'python_basics',
      prompt: 'What will be the resulting value of the expression `15 // 4` in Python?',
      options: [
        '3.75',
        '3',
        '3.0',
        '4'
      ],
      correctIndex: 1,
      hint: 'The `//` operator performs floor division, rounding down to the nearest integer.',
      explanation: 'The floor division operator `//` divides the numbers and slices off any decimal value, returning an integer. $15 / 4$ is $3.75$, hence the floor is $3$.'
    }
  ],
  numpy_essentials: [
    {
      id: 'qb_np_1',
      topicId: 'numpy_essentials',
      prompt: 'What does vectorization in NumPy refer to?',
      options: [
        'Converting scalar functions to work with python standard lists.',
        'Executing array operations without explicit Python `for` loops, leveraging optimized C binaries.',
        'Creating 3D vector graphics matrices.',
        'Slicing lists using coordinate pointers.'
      ],
      correctIndex: 1,
      hint: 'NumPy delegates mathematical loops to compiled, low-level libraries for performance.',
      explanation: 'Vectorization allows operations to execute directly across whole arrays in parallel compile-time speed, bypassing slow python loops.'
    },
    {
      id: 'qb_np_2',
      topicId: 'numpy_essentials',
      prompt: 'What is the shape of `np.array([[1, 2, 3], [4, 5, 6]])`?',
      options: [
        '(3, 2)',
        '(6,)',
        '(2, 3)',
        '(2, 3, 1)'
      ],
      correctIndex: 2,
      hint: 'The array has 2 rows and 3 columns.',
      explanation: 'NumPy shapes list dimensions in order of (rows, columns). There are 2 nested outer brackets, each containing 3 scalars.'
    }
  ],
  pandas_wrangling: [
    {
      id: 'qb_pd_1',
      topicId: 'pandas_wrangling',
      prompt: 'Which Pandas method is used to aggregate data by one or more columns?',
      options: [
        'df.aggregate_by()',
        'df.pivot_table()',
        'df.groupby()',
        'df.split()'
      ],
      correctIndex: 2,
      hint: 'This method is similar to SQL GROUP BY syntax.',
      explanation: '`df.groupby()` splits the DataFrame into subsets by columns, allowing aggregate operations like `.sum()` or `.mean()` to be chained.'
    },
    {
      id: 'qb_pd_2',
      topicId: 'pandas_wrangling',
      prompt: 'How do you filter a DataFrame `df` to keep only rows where the column "sales" is greater than 10,000?',
      options: [
        'df.filter(df["sales"] > 10000)',
        'df[df["sales"] > 10000]',
        'df.loc["sales" > 10000]',
        'df.query(sales > 10000)'
      ],
      correctIndex: 1,
      hint: 'This uses boolean indexing by passing a comparison array inside selection brackets.',
      explanation: '`df[df["sales"] > 10000]` uses boolean filtering. It creates a mask of True/False values and filters the rows accordingly.'
    }
  ],
  sql_queries: [
    {
      id: 'qb_sql_1',
      topicId: 'sql_queries',
      prompt: 'In SQL, which clause is used to filter records generated by aggregate groupings?',
      options: [
        'WHERE',
        'HAVING',
        'FILTER',
        'QUALIFY'
      ],
      correctIndex: 1,
      hint: 'The WHERE clause filters rows BEFORE aggregation. This clause filters groups AFTER aggregation.',
      explanation: '`HAVING` is executed after the GROUP BY statement, meaning it evaluates groupings, while `WHERE` evaluates original rows.'
    },
    {
      id: 'qb_sql_2',
      topicId: 'sql_queries',
      prompt: 'What type of JOIN returns all rows from the left table and matched rows from the right table?',
      options: [
        'INNER JOIN',
        'FULL OUTER JOIN',
        'LEFT JOIN',
        'CROSS JOIN'
      ],
      correctIndex: 2,
      hint: 'It prioritizes the source dataset declared on the left side of the JOIN syntax.',
      explanation: 'A `LEFT JOIN` or `LEFT OUTER JOIN` preserves all rows of the left dataset, filling right side variables with NULLs if there is no match.'
    }
  ],
  statistics: [
    {
      id: 'qb_stat_1',
      topicId: 'statistics',
      prompt: 'What does a p-value of 0.03 indicate if our confidence alpha threshold is set to 0.05?',
      options: [
        'Accept the Null Hypothesis; no statistically significant variance.',
        'Reject the Null Hypothesis; evidence of a statistically significant effect.',
        'The experiment is corrupt and has 3% noise.',
        'The statistical power of the test is 97%.'
      ],
      correctIndex: 1,
      hint: 'If the p-value is less than alpha, we reject the null hypothesis.',
      explanation: 'Since $0.03 < 0.05$, the probability of seeing this outcome by random luck is extremely small, meaning we reject the null hypothesis.'
    }
  ]
};

interface PracticeTabProps {
  initialTopicId: string | null;
  onNavigateToTab: (tabId: string) => void;
}

export const PracticeTab: React.FC<PracticeTabProps> = ({ initialTopicId, onNavigateToTab }) => {
  const [activeTopicId, setActiveTopicId] = useState<string>('python_basics');
  const [topicMetadata, setTopicMetadata] = useState<TopicMetadata | null>(null);
  const [questions, setQuestions] = useState<Question[]>([]);
  const [currentIdx, setCurrentIdx] = useState(0);
  const [selectedOpt, setSelectedOpt] = useState<number | null>(null);
  const [answered, setAnswered] = useState(false);
  const [revealedHint, setRevealedHint] = useState(false);
  
  // Scoring parameters
  const [correctAnswers, setCorrectAnswers] = useState(0);
  const [hintsUsed, setHintsUsed] = useState(0);
  const [quizComplete, setQuizComplete] = useState(false);
  
  // Timer
  const [startTime, setStartTime] = useState<number>(Date.now());
  const [seconds, setSeconds] = useState(0);

  // Sync with clicked curriculum selector
  useEffect(() => {
    if (initialTopicId) {
      setActiveTopicId(initialTopicId);
    }
  }, [initialTopicId]);

  useEffect(() => {
    async function loadTopicQuestions() {
      const metadata = await db.topics.get(activeTopicId);
      if (metadata) {
        setTopicMetadata(metadata);
      }
      
      const qList = QUESTION_BANK[activeTopicId] || QUESTION_BANK['python_basics'];
      setQuestions(qList);
      
      // Reset quiz parameters
      setCurrentIdx(0);
      setSelectedOpt(null);
      setAnswered(false);
      setRevealedHint(false);
      setCorrectAnswers(0);
      setHintsUsed(0);
      setQuizComplete(false);
      setStartTime(Date.now());
      setSeconds(0);
    }
    loadTopicQuestions();
  }, [activeTopicId]);

  // Keep-alive timer
  useEffect(() => {
    if (quizComplete) return;
    const interval = setInterval(() => {
      setSeconds(Math.floor((Date.now() - startTime) / 1000));
    }, 1000);
    return () => clearInterval(interval);
  }, [startTime, quizComplete]);

  const handleSelectOption = (idx: number) => {
    if (answered) return;
    setSelectedOpt(idx);
  };

  const handleSubmitAnswer = () => {
    if (selectedOpt === null || answered) return;
    setAnswered(true);

    const q = questions[currentIdx];
    if (selectedOpt === q.correctIndex) {
      setCorrectAnswers(prev => prev + 1);
    }
  };

  const handleNext = async () => {
    if (currentIdx + 1 < questions.length) {
      setCurrentIdx(prev => prev + 1);
      setSelectedOpt(null);
      setAnswered(false);
      setRevealedHint(false);
    } else {
      // Quiz complete!
      setQuizComplete(true);
      
      // Update database using Learning Engine
      const scorePercent = Math.round((correctAnswers / questions.length) * 100);
      await LearningEngine.recordPracticeSession({
        topicId: activeTopicId,
        scorePercent,
        hintsUsed,
        isChallenge: false,
        secondsTaken: seconds
      });
    }
  };

  const handleRevealHint = () => {
    if (revealedHint) return;
    setRevealedHint(true);
    setHintsUsed(prev => prev + 1);
  };

  return (
    <div className="max-w-3xl mx-auto rounded-2xl border border-slate-800 bg-slate-900/40 p-6 md:p-8 animate-fade-in">
      
      {/* Quiz Header Selector */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between border-b border-slate-800/80 pb-6 mb-6 gap-4">
        <div>
          <div className="flex items-center gap-2">
            <span className="rounded bg-indigo-500/10 px-2.5 py-1 font-mono text-[10px] font-bold text-indigo-400 uppercase tracking-wide">
              Module Sandbox
            </span>
            <div className="flex items-center gap-1.5 font-mono text-xs text-slate-400">
              <Clock className="h-3.5 w-3.5 text-slate-500" />
              <span>{Math.floor(seconds / 60)}m {seconds % 60}s</span>
            </div>
          </div>
          <h2 className="text-xl font-bold text-white mt-1">
            {topicMetadata ? topicMetadata.title : 'Data Analyst Training'}
          </h2>
        </div>

        {/* Dynamic selector to practice other nodes */}
        <select 
          value={activeTopicId}
          onChange={(e) => setActiveTopicId(e.target.value)}
          className="rounded-lg border border-slate-800 bg-slate-950 px-3 py-2 text-xs font-mono text-slate-200 outline-none hover:border-slate-700 focus:border-indigo-500 transition-colors"
        >
          <option value="python_basics">Python Core Variables</option>
          <option value="numpy_essentials">NumPy Arrays & Math</option>
          <option value="pandas_wrangling">Pandas Wrangling</option>
          <option value="sql_queries">SQL Joins & Grouping</option>
          <option value="statistics">Hypothesis Statistics</option>
        </select>
      </div>

      {!quizComplete ? (
        questions.length > 0 ? (
          <div className="space-y-6">
            
            {/* Progress breadcrumbs */}
            <div className="flex justify-between items-center text-xs font-mono text-slate-400">
              <span>QUESTION {currentIdx + 1} OF {questions.length}</span>
              <span className="text-[10px] uppercase text-indigo-400 font-bold">Passing requirement: 70%+</span>
            </div>

            {/* Question prompt block */}
            <div className="rounded-xl bg-slate-950 p-5 border border-slate-900">
              <p className="text-sm md:text-base font-semibold leading-relaxed text-slate-200">
                {questions[currentIdx].prompt}
              </p>
            </div>

            {/* Answer Options listing */}
            <div className="grid grid-cols-1 gap-3">
              {questions[currentIdx].options.map((option, idx) => {
                const isSelected = selectedOpt === idx;
                const showCorrect = answered && idx === questions[currentIdx].correctIndex;
                const showIncorrect = answered && isSelected && idx !== questions[currentIdx].correctIndex;

                return (
                  <button
                    key={idx}
                    onClick={() => handleSelectOption(idx)}
                    disabled={answered}
                    className={`flex items-center justify-between rounded-xl border p-4 text-left text-sm font-medium transition-all duration-150 ${
                      showCorrect 
                        ? 'bg-emerald-500/10 border-emerald-500 text-emerald-400' 
                        : showIncorrect 
                          ? 'bg-rose-500/10 border-rose-500 text-rose-400'
                          : isSelected 
                            ? 'bg-indigo-600/10 border-indigo-500 text-indigo-300' 
                            : 'bg-slate-950/60 border-slate-900 text-slate-300 hover:border-slate-800 hover:bg-slate-950'
                    }`}
                  >
                    <span>{option}</span>
                    <div className={`flex h-5 w-5 items-center justify-center rounded-full border ${
                      showCorrect ? 'border-emerald-500 bg-emerald-500 text-slate-900' :
                      showIncorrect ? 'border-rose-500 bg-rose-500 text-slate-900' :
                      isSelected ? 'border-indigo-500 bg-indigo-500 text-slate-950' : 'border-slate-800'
                    }`}>
                      {showCorrect ? (
                        <CheckCircle className="h-4 w-4" />
                      ) : showIncorrect ? (
                        <XCircle className="h-4 w-4" />
                      ) : isSelected ? (
                        <div className="h-2 w-2 rounded-full bg-indigo-400" />
                      ) : null}
                    </div>
                  </button>
                );
              })}
            </div>

            {/* Action buttons footer */}
            <div className="flex flex-col sm:flex-row gap-3 pt-4 justify-between">
              
              {/* Hint Trigger */}
              <div>
                {!revealedHint ? (
                  <button
                    onClick={handleRevealHint}
                    className="flex items-center gap-1.5 rounded-lg border border-slate-800 bg-slate-950 text-slate-400 hover:bg-slate-800 hover:text-white px-4 py-2 text-xs font-semibold transition-colors"
                  >
                    <HelpCircle className="h-4 w-4" />
                    <span>Need a Hint?</span>
                  </button>
                ) : (
                  <div className="rounded-lg bg-indigo-500/5 border border-indigo-500/15 p-3 text-xs text-indigo-300 max-w-sm">
                    <strong>Hint:</strong> {questions[currentIdx].hint}
                  </div>
                )}
              </div>

              {/* Submit / Next navigation */}
              <div>
                {!answered ? (
                  <button
                    onClick={handleSubmitAnswer}
                    disabled={selectedOpt === null}
                    className="w-full sm:w-auto flex items-center justify-center gap-2 rounded-xl bg-indigo-600 hover:bg-indigo-500 disabled:opacity-40 disabled:cursor-not-allowed text-white px-6 py-2.5 text-xs font-bold transition-all shadow-lg"
                  >
                    <span>Submit Answer</span>
                  </button>
                ) : (
                  <button
                    onClick={handleNext}
                    className="w-full sm:w-auto flex items-center justify-center gap-2 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white px-6 py-2.5 text-xs font-bold transition-all shadow-lg"
                  >
                    <span>{currentIdx + 1 < questions.length ? 'Next Question' : 'Complete Quiz'}</span>
                    <ChevronRight className="h-4 w-4" />
                  </button>
                )}
              </div>

            </div>

            {/* Explanation box */}
            {answered && (
              <div className="animate-fade-in rounded-xl bg-slate-950 p-4 border border-slate-900 space-y-1.5">
                <span className="text-[10px] font-mono text-indigo-400 uppercase font-bold tracking-wider">Concept Explanation:</span>
                <p className="text-xs text-slate-300 leading-relaxed">{questions[currentIdx].explanation}</p>
              </div>
            )}

          </div>
        ) : (
          <div className="text-center py-10 text-slate-500">No questions seeded yet.</div>
        )
      ) : (
        <div className="text-center py-8 space-y-6 animate-fade-in">
          {/* Quiz Completed Summary */}
          <div className="inline-flex h-16 w-16 items-center justify-center rounded-full bg-emerald-500/10 text-emerald-400 border border-emerald-500/30">
            <CheckCircle className="h-10 w-10" />
          </div>

          <div className="space-y-2">
            <h3 className="text-xl font-bold text-white">Interactive Session Complete!</h3>
            <p className="text-sm text-slate-400 max-w-md mx-auto">
              Your results are synced with the local IndexedDB progress engine. Knowledge Graph weights adjusted.
            </p>
          </div>

          {/* Results Score Metrics card */}
          <div className="grid grid-cols-3 gap-3 max-w-sm mx-auto font-mono text-xs text-slate-400">
            <div className="rounded-xl bg-slate-950 p-4 border border-slate-900">
              <div className="text-slate-500 text-[10px]">CORRECT</div>
              <div className="text-base font-bold text-emerald-400">{correctAnswers} / {questions.length}</div>
            </div>
            <div className="rounded-xl bg-slate-950 p-4 border border-slate-900">
              <div className="text-slate-500 text-[10px]">XP GAINED</div>
              <div className="text-base font-bold text-indigo-400">+{correctAnswers * 40} XP</div>
            </div>
            <div className="rounded-xl bg-slate-950 p-4 border border-slate-900">
              <div className="text-slate-500 text-[10px]">HINTS USED</div>
              <div className="text-base font-bold text-slate-300">{hintsUsed}</div>
            </div>
          </div>

          <div className="pt-4 flex flex-col sm:flex-row gap-3 justify-center">
            <button
              onClick={() => onNavigateToTab('dashboard')}
              className="flex items-center justify-center gap-2 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white px-5 py-2.5 text-xs font-semibold shadow-lg"
            >
              <Zap className="h-4 w-4" />
              <span>Go to Dashboard</span>
            </button>
            <button
              onClick={() => {
                // Restart quiz
                setCurrentIdx(0);
                setSelectedOpt(null);
                setAnswered(false);
                setRevealedHint(false);
                setCorrectAnswers(0);
                setHintsUsed(0);
                setQuizComplete(false);
                setStartTime(Date.now());
                setSeconds(0);
              }}
              className="flex items-center justify-center gap-2 rounded-xl border border-slate-800 bg-slate-900/60 hover:bg-slate-800 text-slate-200 px-5 py-2.5 text-xs font-semibold"
            >
              <span>Practice Again</span>
            </button>
          </div>

        </div>
      )}

    </div>
  );
};
